# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/
# as
# Default language
en:
  languageCode: en-us
  contentDir: content/en
  params:
    tile: LAPA
    description: LAPA's research group

# Other languages
pt:
  languageCode: pt-br
  contentDir: content/pt
  params:
    tile: LAPA
    description: Grupo de pesquisa LAPA